### ISSUE TITLE
keep current lang in navbar links

### ISSUE THREAD

**Issue by jpmarindiaz** [datasketch/pages#23] opened 2021-06-14 14:40 UTC
If I am visiting this page:
datasketch.co/es/carga-de-datos/

When I click on the Aplicaciones button on top I get redirected to `/apps/`instead of `/es/apps`

**Comment by ddazal** [comment] 2021-08-14 15:42
Duplicate of https://github.com/datasketch/pages/issues/15

**Closed by ddazal** 2021-08-14 15:42 UTC
